### ISSUE TITLE
recalculate output when a pip is deleted

### ISSUE THREAD

**Issue by adriennealyzee** [PiP-App/PiP#19]

**Comment by adriennealyzee** [comment]
onScreen for calculating output
called for each output
if offscreen, and none of inputs are onscreen

**Comment by peter-slattery** [comment]
We need to talk about this one. 
Here's my thoughts:
The way we have it set now, we are only tracking the final output of a pip. ie. If I type in textPipA and have it output to textPipB, textPipB's output is the concatenation of A and B. Nowhere are we storing what was typed into B so when A is deleted, there isn't any way to revert to it. 

I think we need to go through and define a series of "myOutput" variables that represent a pips output before any inputs are considered.
