### ISSUE TITLE
make drag speed faster

### ISSUE THREAD

**Issue by adriennealyzee** [PiP-App/PiP#23]

**Comment by peter-slattery** [comment]
What does this mean? Drag speed is the speed you move your finger.

**Comment by adriennealyzee** [comment]
ohhhh there's a lag in dragging for me, but I realize that's only when I'm
zoomed out.

Adrienne Tran
+1 415 994 7670
http://www.adriennetran.com

**Comment by peter-slattery** [comment]
Fixed. Line 364/365 of WorkspaceViewController.
I just divided the UIPanGestureRecognizer translation by the scrollView.zoomScale
